version: 0.2

phases:
  install:
    commands:
      # Terraform のバージョンを v1.7.0 に更新
      - wget https://releases.hashicorp.com/terraform/1.7.0/terraform_1.7.0_linux_amd64.zip
      - unzip terraform_1.7.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      # 指定のディレクトリへ移動
      - cd ./environments/production
      - terraform init
  build:
    commands:
      # 指定のディレクトリで Terraform apply を実行
      - pwd
      - terraform apply -auto-approve
